InstallMethod(PE_ValidAutomizers, "method for finding valid automizers", 
    [IsPGroup, IsPGroup], function(S, E)
    local   AutE, # Aut(E)
            InnE, # Inn(E)
            AutSE, # Aut_S(E)
            p, # the prime
            n, # the nice monomorphism for Aut(E)
            L, # possible choices for Aut_F(E)
            i, # current position in L
            AutFE, # possible Aut_F(E)
            A, # O_p(Aut_F(E))
            q, # quotient map Aut_F(E) -> Aut_F(E)/A
            OutFE, # quotient Aut_F(E)/A
            OutSE, # quotient Aut_S(E)/A
            OutE, # quotient Aut(E)/A
            M, # the maximal subgroups of OutFE
            C, # the conjugates of subgroups in M containing OutSE
            I, # positions of conjugates in C containing OutSE
            a, # counter of new automizers
            X; # a subgroup in C or L

    p := PrimePGroup(S);

    AutE := AutomorphismGroup(E);
    n := NiceMonomorphism(AutE);
    InnE := Automizer(E, E);
    AutSE := Automizer(S, E);
    AutE := NiceObject(AutE);

    if IsBound(AutE!.autrec) then 
        InnE := PcSubAutPGroup(AutE, InnE);
        AutSE := PcSubAutPGroup(AutE, AutSE);
    else 
        InnE := Image(n, InnE);
        AutSE := Image(n, AutSE);
    fi;

    # Find subgroups containing AutSE within overgroups above p-core. Iterated maximal approach
    L := [PrimeResidual(AutE,p)];
    i := 0;

    while i < Length(L) do 
        i := i+1;
        AutFE := L[i];
        A := PCore(AutFE,p);

        q := NaturalHomomorphismByNormalSubgroup(AutFE, A);
        
        OutFE := Image(q);
        OutSE := Image(q, AutSE);
        Info(InfoFusion, 4, "\tFound section of order ", Size(OutFE));
        
        M := MaximalSubgroupClassReps(OutFE);
        Info(InfoFusion, 4, "\t\twhich has ", Length(M), " maximal subgroups");
        M := List(M, A -> PrimeResidual(A,p));
        C := List(M, A -> ContainedConjugates(OutFE, A, OutSE, true));
        I := PositionsProperty(C, A -> A <> fail);
        Info(InfoFusion, 4, "\t\tof which ", Length(I), " contain Aut_S(E)");

        C := List(I, i -> M[i]^(C[i][2]^-1));
        C := List(C, A -> PreImage(q, A));

        a := 0;
        # Add missing G-conjugates
        for X in C do 
            if Intersection(PCore(X,p), AutSE) = InnE and ForAll(L, T -> not IsConjugate(AutE, T, X)) then 
                a := a+1;
                Add(L, X);
            fi;
        od;
        Info(InfoFusion, 4, "\t\tTotal ", a, " new automizer(s) up to Aut(E)-conjugacy");
    od;

    q := NaturalHomomorphismByNormalSubgroup(AutE, InnE);
    OutE := Image(q);
    L := Filtered(L, A -> IndexNC(A, ClosureGroup(AutSE, PCore(A,p))) mod p <> 0);
    L := List(L, A -> Image(q, A));
    OutSE := Image(q, AutSE);

    Info(InfoFusion, 4, "\t", Length(L), " possible valid radical automizer(s) (mod p-core)");

    # TODO: Filter the elements in L that have a strongly p-embedded subgroup (mod p-core)
    Info(InfoFusion, 4, "\t", Length(L), " possible valid essential automizer(s) (mod p-core)");

    L := List(L, A -> ComplementClassesRepresentatives(A, PCore(A,p)));
    L := Flat(L);

    C := List(L, A -> RepresentativeAction(OutE, SylowSubgroup(A,p), OutSE));
    I := PositionsProperty(C, A -> A <> fail);
    L := List(I, i -> L[i]^C[i]);
    L := List(L, A -> PreImage(q, A));
    Info(InfoFusion, 4, Length(L), " valid essential automizer(s)");

    L := List(L, A -> PreImage(n, A));

    for X in L do 
        SetIsGroupOfAutomorphismsFiniteGroup(X, true);
        SetAutomorphismDomain(X, E);
    od;

    return L;
end );

# Finds the subgroup of $\Aut(S)$ generated by extensions of $N_{\Aut_\calF(E)}(\Aut_S(E))$ (for $E$ maximal essential)
InstallMethod(FindSmallestBorel, "find smallest Borel", 
    [IsPGroup, IsGroupOfAutomorphismsFiniteGroup], function(S, AutFE)
    local E, AutSE, n, N, AutS, g, e;

    E := AutomorphismDomain(AutFE);
    AutSE := Automizer(S, E);

    n := NiceMonomorphism(AutFE);
    AutFE := n(AutFE);
    AutSE := n(AutSE);
    N := Normalizer(AutFE, AutSE);
    N := PreImage(n, N);

    AutS := AutomorphismGroup(S);
    n := NiceMonomorphism(AutS);
    AutS := n(AutS);

    g := GeneratorsOfGroup(E);

    e := List(GeneratorsOfGroup(N), a -> RepresentativeAction(AutS, g, List(g, x -> a(x)), OnImageTuplesNM(n)));

    if ForAny(e, x -> x = fail) then 
        return fail;
    fi;

    return Group(e);
end );

IsFullyNormalizedInSequence := function(S, AutFE0, E)
    local n, O;

    n := NiceMonomorphism(AutFE0);
    AutFE0 := n(AutFE0);

    # check that amongst subs $F \in E^\Aut_F(E_0)$, we have that $|N_S(F)| >= |N_S(E)|$
    O := Orbit(AutFE0, E, OnImageNM(n));

    return ForAll(O, E0 -> IndexNC(Normalizer(S,E), E) >= IndexNC(Normalizer(S, E0), E0));
end;

InstallMethod(IsAutomizerBorelCompatible, "check automizer is Borel-compatible", 
    [IsPGroup, IsGroupOfAutomorphismsFiniteGroup, IsGroupOfAutomorphismsFiniteGroup], function(S, AutFS, AutFE)
    local p, E, AutF0E, AutE, n, A0;

    p := PrimePGroup(S);
    E := AutomorphismDomain(AutFE);
    AutF0E := RestrictedAutomorphismStabilizerSubgroup(AutFS, E);

    AutE := AutomorphismGroup(E);
    n := NiceMonomorphism(AutE);

    A0 := ClosureGroup(AutFE, AutF0E);
    A0 := n(A0);
    AutFE := n(AutFE);
    
    return PrimeResidual(A0, p) = AutFE;
end);

# Checks whether the smallest choice for the focal subgroup in the fusion system
# is actually $S$. Currently, the subgroup $B$ is not guaranteed to actually 
# equal $\Aut_F^0(S)$.
InstallMethod(IsFocalCompatibleSequence, "check focal subgroup is the entire group", 
    [IsPGroup, IsGroupOfAutomorphismsFiniteGroup, IsGroupOfAutomorphismsFiniteGroup], function(S, B, P)
    local A, i, A0;

    A := AutCommutatorSubgroup(B, S);

    for i in [1..Length(P)] do 
        A0 := AutCommutatorSubgroup(P[i], AutomorphismDomain(P[i]));
        A := ClosureGroup(A, A0);
    od;

    return A = S;
end);

InstallMethod(IsCompatibleSequence, "check sequence compatible", 
    [IsPGroup, IsGroupOfAutomorphismsFiniteGroup], function(S, P)
    local p, L, tau, AutS, InnS, n, B, I, i, J, Ext, J0;

    p := PrimePGroup(S);
    L := List(P, AutomorphismDomain);
    tau := Sortex(List(L, Size));
    
    L := Permuted(L, tau);
    P := Permuted(P, tau);

    L := Reversed(L);
    P := Reversed(P);
    
    AutS := AutomorphismGroup(S);
    n := NiceMonomorphism(AutS);
    InnS := InnerAutomorphismGroup(S);
    
    InnS := n(InnS);
    AutS := n(AutS);

    B := InnS;

    # TODO: Should try to compute $E^\calF$ here for accuracy
    for i in [1..Length(L)] do 
        # TODO: Up to F-conjugacy here
        J := List([1..i-1], j -> ContainedConjugates(S, L[j], L[i], true));
        if ForAll(J, i -> i = fail) then 
            Info(InfoWarning, 1, "E is maximal essential");
            Ext := FindSmallestBorel(S, P[i]);
            # should be maximal essential here
            if Ext = fail then 
                Info(InfoWarning, 1, "Maps don't extend to S");
                return false;
            fi;
            Info(InfoWarning, 1, "Maps extend to S");
            B := ClosureGroup(B, Ext);
            if IndexNC(B, InnS) mod p = 0 then 
                Info(InfoWarning, 1, "S no longer fully automized");
                return false;
            fi;
        else 
            Info(InfoWarning, 1, "E is not maximal essential");
            J0 := PositionsProperty(J, i -> i <> fail);
            # TODO: Conjugate the proto-essential automizer choices by the conjugating element
            if ForAny(J0, j -> not IsFullyNormalizedInSequence(S, P[j]^J[j][2], L[i])) then 
                Info(InfoWarning, 1, "E not fully normalized with respect to some larger essential");
                return false;
            fi;
            Info(InfoWarning, 1, "E fully normalized with respect to some larger essential");
        fi;
    od;

    # After finding the choice containing $\Aut_F^0(S)$, check that this restricts nicely to each automizer in the sequence,
    # i.e. $O^{p'}(\Aut_\calF(E^{(0)}))$ is part of the sequence ($E^{(0)}$ contains the restrictions from the group)
    B := PreImage(n, B);
    # TODO: We actually need the stronger condition to hold here! (make it a fn) -- if this gets bigger e.g. $\Alt(4)$ to $\Alt(5)$,
    # the $\Alt(4)$ version is invalid here -- we need the $\Alt(5)$ version to pass instead
    if ForAny(P, AutFE -> not IsAutomizerBorelCompatible(S, B, AutFE)) then 
        Info(InfoWarning, 1, "The automizer sequence doesn't have a valid Borel subgroup");
        return false;
    fi;

    Info(InfoWarning, 1, "Compatible focal = ", IsFocalCompatibleSequence(S, B, P));
    # This compatible sequence will likely further check for saturation on $\calF^{cr}$, the ultimate test for saturation

    return true;
end );

GetSequence := function(A, P)
    local U, i;

    U := [];
    for i in [1..Length(A)] do 
        if A[i] > 0 then 
            Add(U, P[i][A[i]]);
        fi;
    od;

    return U;
end;

FilterCorefreeSequences := function(S, L, P, D)
    local N, NP;
    
    N := NormalSubgroups(S);
    NP := List([1..Length(P)], i -> List(P[i], AutFE -> PositionsProperty(N, A -> IsSubset(L[i], A) and 
        ForAll(GeneratorsOfGroup(AutFE), phi -> Image(phi, A) = A))));

    return Filtered(D, A -> Length(Intersection(GetSequence(A, NP))) = 1);
end;

InstallMethod(FindReducedSequences, "find reduced sequences",
    [IsPGroup, IsList], function(S, L)
    local IsSubSequence, P, I, D, ValidSequences, InvalidSequences, A, U;

    # checks whether one combination is a sub-combination of the other
    IsSubSequence := function(A, B)
        return ForAll([1..Length(A)], i -> A[i] = 0 or A[i] = B[i]);
    end;

    Info(InfoWarning, 1, "Finding valid automizers");
    P := List(L, E -> PE_ValidAutomizers(S, E));
    I := PositionsProperty(L, A -> not IsEmpty(A));
    
    P := P{I};
    L := L{I};
    
    Info(InfoWarning, 1, "Checking whether combinations are valid");

    D := Cartesian(List(P, A -> [0..Length(A)])); # 0 represents the subgroup is not essential
    D := FilterCorefreeSequences(S, L, P, D);
    Info(InfoWarning, 1, Length(D), " Corefree possibilities");

    ValidSequences := [];
    InvalidSequences := [];
    for A in D do 
        Info(InfoWarning, 1, "Checking combination ", A);

        if ForAny(InvalidSequences, B -> IsSubSequence(B, A)) then 
            Info(InfoWarning, 1, "Contains an incompatible sequence");
            continue;
        fi;

        U := GetSequence(A, P);

        if IsCompatibleSequence(S, U) then 
            Info(InfoWarning, 1, "Valid");
            Add(ValidSequences, A);
        else 
            Add(InvalidSequences, A);
        fi;
    od;

    return ValidSequences;
end );

# For PE_ValidAutomizers, we should expect the number of $\Out(E)$-conjugates of $\Out_F(E)$ to equal the number of $\Out(S)|_E$-conjugates of $\Out_F(E)$.

InstallMethod(IsomorphismSequences, "find isomorphism between automizer sequences",
    [IsPGroup, IsList, IsList], function(S, P1, P2)
    local AutS, n;
    
    if Length(P1) <> Length(P2) then 
        return fail;
    fi;

    AutS := AutomorphismGroup(S);
    n := NiceMonomorphism(AutS);

    # Need to allow OnPoints (i.e. \^) to get conjugated by any automorphism of an overgroup
    return RepresentativeAction(AutS, P1, P2, OnImageTuplesNM(n));
end);
